### ISSUE TITLE
'd_C(4)' doesn‘t appear to be assigned.

### ISSUE THREAD

**Issue by Cherrrrrity** [wengensheng/BiomeESS#4]
Hello, Professor.Weng,
I found 'd_C(4)' doesn‘t appear to be assigned. Could you please help to have a look? Thank you~
scr/soil.F90: line 69-74
```fortran
! Turnover in SOM4 and SOM5
  do i=3, 5
     !d_C(i) = vegn%SOC(i)*(1. - exp(-A*K0SOM(i)*dt_fast_yr))
     d_C(i) = vegn%SOC(i) * A * K0SOM(i) * dt_fast_yr
     d_N(i) = vegn%SON(i) * A * K0SOM(i) * dt_fast_yr
  enddo

**Comment by wengensheng** [comment]
It is from 3 to 5. So, the loop will do3, 4, and 5.On Mar 13, 2023, at 10:43 PM, LiutingChen ***@***.***> wrote:﻿
Hello, Professor.Weng,
I find 'd_C(4)' doesn‘t appear to be assigned. Could you please help to have a look? Thank you~
scr/soil.F90: line 69-74
! Turnover in SOM4 and SOM5
  do i=3, 5
     !d_C(i) = vegn%SOC(i)*(1. - exp(-A*K0SOM(i)*dt_fast_yr))
     d_C(i) = vegn%SOC(i) * A * K0SOM(i) * dt_fast_yr
     d_N(i) = vegn%SON(i) * A * K0SOM(i) * dt_fast_yr
  enddo

**Comment by Cherrrrrity** [comment]
Oh! Thank you for your reply, Professor!
